name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Show kernel version
      run: uname -s -r
    - name: Install kernel headers
      run: sudo apt install -y linux-headers-$(uname -r)
    - name: Build the module
      run: make
    - name: Show THP status
      run: ./scripts/show-thp.sh
