name: build and test kernel module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Show kernel version
      run: uname -s -r
    - name: Install kernel headers
      run: sudo apt install -y linux-headers-$(uname -r)
    - name: Build the module
      run: make
    - name: Show THP status BEFORE moving to madvise
      run: ./scripts/show-thp.sh
    - name: Set THP status to madvise
      run: sudo ./scripts/disable-thp-madvise.sh
    - name: Show THP status AFTER moving to madvise
      run: ./scripts/show-thp.sh
    - name: Clear dmesg
      run: sudo dmesg --clear
    - name: Setup kernel module
      run: sudo make module-mount
    - name: Finally, run tests
      run: sudo make run-tests
    - name: Teardown kernel module
      run: sudo make module-umount
    - name: Show dmesg
      run: sudo dmesg
