name: build and test kernel module, then run examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Show kernel version
      run: uname -s -r
    - name: Update apt sources
      run: sudo apt update
    - name: Install kernel headers and libnl-3
      run: sudo apt install -y linux-headers-$(uname -r) libnl-3-dev libnl-genl-3-dev
    - name: Build the module
      run: make kernel-testing
    - name: Show THP status BEFORE moving to madvise
      run: ./scripts/show-thp.sh
    - name: Set THP status to madvise
      run: sudo ./scripts/disable-thp-madvise.sh
    - name: Show THP status AFTER moving to madvise
      run: ./scripts/show-thp.sh
    - name: Clear dmesg
      run: sudo dmesg --clear
    - name: Setup kernel module
      run: sudo make module-mount
    - name: Finally, run tests
      run: sudo make BUILD_TYPE=no-fail run-tests
    - name: Show dmesg
      if: always()
      run: sudo dmesg
    - name: Run examples
      run: sudo make run-examples
    - name: Clear dmesg
      run: sudo dmesg --clear
    - name: Teardown kernel module
      run: sudo make module-umount
    - name: Show dmesg
      if: always()
      run: sudo dmesg

